# Generated by Django 2.2.3 on 2019-07-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kebun_Binatang', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hewan',
            options={'verbose_name': 'Hewan', 'verbose_name_plural': 'Hewan'},
        ),
        migrations.AlterModelOptions(
            name='kandang',
            options={'verbose_name': 'Kandang', 'verbose_name_plural': 'Kandang'},
        ),
        migrations.AlterModelOptions(
            name='pengunjung',
            options={'verbose_name': 'Pengunjung', 'verbose_name_plural': 'Pengunjung'},
        ),
        migrations.AlterModelOptions(
            name='penjaga',
            options={'verbose_name': 'Penjaga', 'verbose_name_plural': 'Penjaga'},
        ),
        migrations.AlterField(
            model_name='pengunjung',
            name='hari_berkunjung',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='penjaga',
            name='jadwal_jaga',
            field=models.TimeField(),
        ),
    ]
