# Generated by Django 2.2.3 on 2019-07-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_mentor_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=255)),
                ('foto', models.CharField(default='a', max_length=255)),
            ],
        ),
    ]
