# Generated by Django 2.2.3 on 2019-07-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rumah_Sakit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasien',
            name='nomor_telpon',
            field=models.CharField(max_length=255),
        ),
    ]
