# Generated by Django 2.2.3 on 2019-07-22 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rumah_Sakit', '0002_auto_20190722_0906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dokter',
            options={'verbose_name': 'Dokter', 'verbose_name_plural': 'Dokter'},
        ),
        migrations.AlterModelOptions(
            name='obat',
            options={'verbose_name': 'Obat', 'verbose_name_plural': 'Obat'},
        ),
        migrations.AlterModelOptions(
            name='pasien',
            options={'verbose_name': 'Pasien', 'verbose_name_plural': 'Pasien'},
        ),
        migrations.AlterModelOptions(
            name='resep',
            options={'verbose_name': 'Resep', 'verbose_name_plural': 'Resep'},
        ),
    ]
